import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { Nav } from '@/components/nav';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body>
        <main>
          <Nav />
          <div className="grid grid-cols-8 px-3 md:grid-cols-16 lg:grid-cols-24">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
